### ISSUE TITLE
Build fails when following readme

### ISSUE THREAD

**Issue by MatthewTingum** [enjoy-digital/pcie_screamer#5]
I run into this issue when building:
```
$ ./pcie_screamer.py --build
Traceback (most recent call last):
  File "./pcie_screamer.py", line 23, in <module>
    from gateware.usb import USBCore
  File "/home/user/Documents/xbleech/pcie_screamer/gateware/usb.py", line 11, in <module>
    from litex.soc.interconnect.wishbonebridge import WishboneStreamingBridge
ModuleNotFoundError: No module named 'litex.soc.interconnect.wishbonebridge'
```

I see that the README guides the the user to grab the latest master from `litex`.
```
wget https://raw.githubusercontent.com/enjoy-digital/litex/master/litex_setup.py
```

I'm sure you can see where this is going, but the `litex` API is subject to change. I haven't done a deep dive, but my best guess is that the `litex` API changed.

I suggest submoduling in the repo at a specific commit or providing a permalink to this file at a specific commit. I see that the `litex_setup.py` script uses python to pull in submodules. Hopefully their not grabbing their submodules from master.

Would a docker image help alleviate this issue?

**Comment by enjoy-digital** [comment]
Thanks @MatthewTingum for the feedback, I just updated the design with https://github.com/enjoy-digital/pcie_screamer/commit/25b071bb917b512e679a943813ea70e22a97ec00.
